//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aoc2020.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aoc2020.Tests.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFFBFBFLRL
        ///BFBFBBBLRR
        ///BFBFBFBLRR
        ///BFBFFFFRLR
        ///BBFFBBFRRR
        ///FBBBFFFRLL
        ///FFBFBFFLLL
        ///BBFBFFFRLL
        ///FBBBFFBLRR
        ///FFFFBFFRRL
        ///BFBFBFBRLL
        ///FFBFFBBLLL
        ///BFFBBFFRLR
        ///FBBFFFFLRR
        ///FBFBFFBRRR
        ///FFBFFBBRRR
        ///FBBBFFFRRL
        ///FFBBBBFRRL
        ///BFFBBBBLLL
        ///BFBBFBBLLR
        ///FBBFBFFLLR
        ///FBBFBFFLRR
        ///BFFFFBFLLL
        ///FBBBBBBRRR
        ///FBFFBBFLLR
        ///BBFBFFBRLR
        ///FFFFFBBLLR
        ///FBBFBBBRLL
        ///FFFFBBFRRR
        ///FFFFBFBLRL
        ///FFFBFBFLLR
        ///FFBFBBBLRR
        ///BFFBBBFRLR
        ///FFFBFBBLLL
        ///FBFBBBFLRR
        ///BBFFFBFLLL
        ///FFFFFBBLRR
        ///FFBFBFFRLL
        ///BFFFBBFRLR
        ///BFBBBFBLLR
        ///FFFBBFFLRL
        ///BFBBBFBLLL
        ///FBFBBFBRLR
        ///BBFFBFFRRR
        ///BFFFFBBLRR
        ///FBBBBBFLRL
        ///FBFBBB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinaryBoardingInput {
            get {
                return ResourceManager.GetString("BinaryBoardingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mswxhfpl
        ///xmhulfp
        ///jhglrxfvmp
        ///xtldhmpf
        ///
        ///c
        ///c
        ///lc
        ///c
        ///
        ///zxe
        ///ex
        ///oxncuje
        ///vdex
        ///devx
        ///
        ///xjylztwnkbma
        ///apxzvjlwnbdyk
        ///zlnbrkyagwjx
        ///ykslxwbjuzang
        ///wjkbylazxne
        ///
        ///aekysof
        ///ecfokmdaysl
        ///ykiosefa
        ///oxsugykeaf
        ///fstyoake
        ///
        ///svzgnfiujobmc
        ///kjlvfbnwimuzdqtgsec
        ///cgijufnsbmzxv
        ///csfnzvujmigb
        ///
        ///jzofxqebrk
        ///zmverjxoafush
        ///ozclfjbierx
        ///jforizlex
        ///
        ///cedziyl
        ///lnemy
        ///
        ///oujdnhgwlqfbmpcrevktaizs
        ///covqbthupgradfnijslexwk
        ///
        ///eawjhlxrtc
        ///ahjlwexcr
        ///
        ///yhnidq
        ///ehznqy
        ///qhyn
        ///hcqny
        ///qywnchd
        ///
        ///skzfnylhmdqcgjoiuv
        ///zwlujnyfismkgdh
        ///nyfxlmiuwdgzkj
        ///jnekmgtdpfuzilbr
        ///
        ///gecslpwytzojbv
        ///retwyjs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomCustomsInput {
            get {
                return ResourceManager.GetString("CustomCustomsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:2015 cid:189 ecl:oth byr:1947 hcl:#6c4ab1 eyr:2026
        ///hgt:174cm
        ///pid:526744288
        ///
        ///pid:688706448 iyr:2017 hgt:162cm cid:174 ecl:grn byr:1943 hcl:#808e9e eyr:2025
        ///
        ///ecl:oth hcl:#733820 cid:124 pid:111220591
        ///iyr:2019 eyr:2001
        ///byr:1933 hgt:159in
        ///
        ///pid:812929897 hgt:159cm hcl:#fffffd byr:1942 iyr:2026 cid:291
        ///ecl:oth
        ///eyr:2024
        ///
        ///cid:83 pid:524032739 iyr:2013 ecl:amb byr:1974
        ///hgt:191cm hcl:#ceb3a1 eyr:2028
        ///
        ///ecl:gry hcl:eefed5 pid:88405792 hgt:183cm cid:221 byr:1963 eyr:2029
        ///
        ///pid:777881168 ecl:grn
        ///hgt:181cm byr:1923 eyr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PassportProcessingInput {
            get {
                return ResourceManager.GetString("PassportProcessingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-11 p: pppppppppxblp
        ///2-4 b: bbxbb
        ///3-5 q: dqfqb
        ///5-8 g: ggcgggglg
        ///10-18 l: gllpmlgtrmnllhllrlll
        ///18-19 z: zzzzznszzzzzzzzzzzxz
        ///3-6 r: frrhxsnrmgmw
        ///1-8 n: zkxhnxnzghnm
        ///11-12 z: zzczzzztlzlzzzz
        ///4-7 q: qqqbncqqq
        ///3-4 c: ccvfc
        ///19-20 l: sltlklljdlzglwllllzl
        ///6-16 h: dhhhrhvhnhdchfsnhq
        ///3-7 l: fllllqjlll
        ///8-9 k: xkkjqklkm
        ///1-2 l: llgpl
        ///2-4 x: qkjxvqlv
        ///5-6 c: cwcccjch
        ///3-7 n: bnnhnwnqtdnndnncnd
        ///8-9 n: nnrkmdnkn
        ///6-9 t: ttttrtltptgvcd
        ///3-4 h: hhwhhhdhhhh
        ///7-8 w: wdwvcwwszcwwwwwq
        ///2-4 n: vnng
        ///3-13 v: vvvvvvvvvvvvjv
        ///9-11 c: zccc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordPhilosophyInput {
            get {
                return ResourceManager.GetString("PasswordPhilosophyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1429
        ///1368
        ///1661
        ///1687
        ///1593
        ///1495
        ///1565
        ///1500
        ///1635
        ///1845
        ///1645
        ///1999
        ///1415
        ///1054
        ///1930
        ///1774
        ///1405
        ///1993
        ///1757
        ///1623
        ///1675
        ///1665
        ///631
        ///1950
        ///1702
        ///1311
        ///1509
        ///1790
        ///1643
        ///1884
        ///226
        ///1455
        ///1679
        ///1746
        ///1284
        ///1342
        ///1684
        ///1543
        ///1396
        ///1806
        ///1523
        ///1363
        ///1011
        ///1577
        ///1767
        ///1287
        ///1885
        ///1517
        ///1556
        ///1722
        ///1260
        ///1624
        ///1466
        ///1263
        ///1162
        ///1688
        ///1202
        ///1913
        ///1964
        ///1385
        ///1970
        ///1976
        ///1431
        ///858
        ///1748
        ///1544
        ///1438
        ///1300
        ///1926
        ///1587
        ///1376
        ///1939
        ///1039
        ///1639
        ///1539
        ///1491
        ///1631
        ///1521
        ///1564
        ///1507
        ///1637
        ///1534
        ///1713
        ///1533
        ///1118
        ///1356
        ///2003
        ///282
        ///1079
        ///1837
        ///1259
        ///1941
        ///1836
        ///1903
        ///1433
        ///1467
        ///1027
        ///1441
        ///1048
        ///1742
        ///1087
        ///1872
        ///1476
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportRepairInput {
            get {
                return ResourceManager.GetString("ReportRepairInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1721
        ///979
        ///366
        ///299
        ///675
        ///1456
        ///.
        /// </summary>
        internal static string ReportRepairSampleInput {
            get {
                return ResourceManager.GetString("ReportRepairSampleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ........#..#.##.#..............
        ///...#...............#.#.........
        ///...#..#...#..##....#...........
        ///...#.............#....#.....#..
        ///..#......#..#...#.......#......
        ///..............##...............
        ///#.......#.........#......#....#
        ///.#.....###.....#...#.#.#...#...
        ///#.....................#....#.#.
        ///.......#...................#...
        ///...#.#...................#....#
        ///....#....#.......#...#.........
        ///..##.#............#..#.........
        ///.....##.#..............##..###.
        ///...........#....#....#.........
        ///#.....#...#...#.#.#.#.##.#...#.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TobogganTrajectoryInput {
            get {
                return ResourceManager.GetString("TobogganTrajectoryInput", resourceCulture);
            }
        }
    }
}
