//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aoc2020.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aoc2020.Tests.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70
        ///102
        ///148
        ///9
        ///99
        ///63
        ///40
        ///52
        ///91
        ///39
        ///55
        ///28
        ///54
        ///22
        ///95
        ///61
        ///118
        ///35
        ///14
        ///21
        ///129
        ///82
        ///137
        ///45
        ///7
        ///87
        ///81
        ///25
        ///3
        ///108
        ///41
        ///11
        ///145
        ///18
        ///65
        ///80
        ///115
        ///29
        ///136
        ///42
        ///97
        ///104
        ///117
        ///141
        ///62
        ///121
        ///23
        ///96
        ///24
        ///128
        ///48
        ///1
        ///112
        ///8
        ///34
        ///144
        ///134
        ///116
        ///58
        ///147
        ///51
        ///84
        ///17
        ///126
        ///64
        ///68
        ///135
        ///10
        ///77
        ///105
        ///127
        ///73
        ///111
        ///90
        ///16
        ///103
        ///109
        ///98
        ///146
        ///123
        ///130
        ///69
        ///133
        ///110
        ///30
        ///122
        ///15
        ///74
        ///33
        ///38
        ///83
        ///92
        ///2
        ///53
        ///140
        ///4
        ///.
        /// </summary>
        internal static string AdapterArrayInput {
            get {
                return ResourceManager.GetString("AdapterArrayInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFFBFBFLRL
        ///BFBFBBBLRR
        ///BFBFBFBLRR
        ///BFBFFFFRLR
        ///BBFFBBFRRR
        ///FBBBFFFRLL
        ///FFBFBFFLLL
        ///BBFBFFFRLL
        ///FBBBFFBLRR
        ///FFFFBFFRRL
        ///BFBFBFBRLL
        ///FFBFFBBLLL
        ///BFFBBFFRLR
        ///FBBFFFFLRR
        ///FBFBFFBRRR
        ///FFBFFBBRRR
        ///FBBBFFFRRL
        ///FFBBBBFRRL
        ///BFFBBBBLLL
        ///BFBBFBBLLR
        ///FBBFBFFLLR
        ///FBBFBFFLRR
        ///BFFFFBFLLL
        ///FBBBBBBRRR
        ///FBFFBBFLLR
        ///BBFBFFBRLR
        ///FFFFFBBLLR
        ///FBBFBBBRLL
        ///FFFFBBFRRR
        ///FFFFBFBLRL
        ///FFFBFBFLLR
        ///FFBFBBBLRR
        ///BFFBBBFRLR
        ///FFFBFBBLLL
        ///FBFBBBFLRR
        ///BBFFFBFLLL
        ///FFFFFBBLRR
        ///FFBFBFFRLL
        ///BFFFBBFRLR
        ///BFBBBFBLLR
        ///FFFBBFFLRL
        ///BFBBBFBLLL
        ///FBFBBFBRLR
        ///BBFFBFFRRR
        ///BFFFFBBLRR
        ///FBBBBBFLRL
        ///FBFBBB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinaryBoardingInput {
            get {
                return ResourceManager.GetString("BinaryBoardingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mswxhfpl
        ///xmhulfp
        ///jhglrxfvmp
        ///xtldhmpf
        ///
        ///c
        ///c
        ///lc
        ///c
        ///
        ///zxe
        ///ex
        ///oxncuje
        ///vdex
        ///devx
        ///
        ///xjylztwnkbma
        ///apxzvjlwnbdyk
        ///zlnbrkyagwjx
        ///ykslxwbjuzang
        ///wjkbylazxne
        ///
        ///aekysof
        ///ecfokmdaysl
        ///ykiosefa
        ///oxsugykeaf
        ///fstyoake
        ///
        ///svzgnfiujobmc
        ///kjlvfbnwimuzdqtgsec
        ///cgijufnsbmzxv
        ///csfnzvujmigb
        ///
        ///jzofxqebrk
        ///zmverjxoafush
        ///ozclfjbierx
        ///jforizlex
        ///
        ///cedziyl
        ///lnemy
        ///
        ///oujdnhgwlqfbmpcrevktaizs
        ///covqbthupgradfnijslexwk
        ///
        ///eawjhlxrtc
        ///ahjlwexcr
        ///
        ///yhnidq
        ///ehznqy
        ///qhyn
        ///hcqny
        ///qywnchd
        ///
        ///skzfnylhmdqcgjoiuv
        ///zwlujnyfismkgdh
        ///nyfxlmiuwdgzkj
        ///jnekmgtdpfuzilbr
        ///
        ///gecslpwytzojbv
        ///retwyjs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomCustomsInput {
            get {
                return ResourceManager.GetString("CustomCustomsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = X1011100000X111X01001000001110X00000
        ///mem[4616] = 8311689
        ///mem[8936] = 240
        ///mem[58007] = 369724
        ///mask = 10X0111X01X0XX110X10100X1001X000010X
        ///mem[41137] = 232605
        ///mem[33757] = 1437435
        ///mask = X0011110100X011X01000X1000X1000X0100
        ///mem[12518] = 27521105
        ///mem[25203] = 3177
        ///mem[33089] = 636515
        ///mem[39100] = 494341
        ///mem[59321] = 16252
        ///mem[55061] = 1075
        ///mask = 1000X11X01X0X01111XX10110001X1110111
        ///mem[16129] = 15646
        ///mem[35714] = 30634
        ///mem[14485] = 6847
        ///mask = 10011110110000X10X0X1010XX1010100X00
        ///mem[2308] = 704945037
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DockingDataInput {
            get {
                return ResourceManager.GetString("DockingDataInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///32
        ///15
        ///49
        ///19
        ///30
        ///50
        ///40
        ///33
        ///45
        ///11
        ///42
        ///26
        ///10
        ///12
        ///5
        ///4
        ///1
        ///27
        ///17
        ///41
        ///43
        ///14
        ///29
        ///18
        ///6
        ///24
        ///16
        ///28
        ///7
        ///8
        ///31
        ///44
        ///9
        ///13
        ///30
        ///85
        ///11
        ///22
        ///10
        ///48
        ///70
        ///15
        ///19
        ///20
        ///17
        ///21
        ///25
        ///14
        ///23
        ///18
        ///26
        ///104
        ///37
        ///16
        ///24
        ///27
        ///28
        ///29
        ///31
        ///32
        ///44
        ///30
        ///46
        ///39
        ///33
        ///35
        ///34
        ///42
        ///36
        ///38
        ///47
        ///72
        ///40
        ///41
        ///43
        ///60
        ///45
        ///48
        ///49
        ///51
        ///55
        ///73
        ///59
        ///69
        ///62
        ///63
        ///65
        ///71
        ///67
        ///68
        ///89
        ///70
        ///74
        ///78
        ///160
        ///81
        ///83
        ///136
        ///90
        ///117
        ///130
        ///99
        ///115
        ///100
        ///106
        ///118
        ///152
        ///121
        ///161
        ///219
        ///184
        ///133
        ///142
        ///145
        ///146
        ///159
        ///164
        ///155
        ///168
        ///171
        ///217
        ///381
        ///252
        ///189
        ///633
        ///205
        ///199
        ///246
        ///221
        ///224
        ///239
        ///301
        ///254
        ///459
        ///275
        ///304
        ///323
        ///287
        ///291
        ///588
        ///392
        ///319
        ///326
        ///475
        ///388
        ///711
        ///394
        ///404
        ///695
        ///429
        ///420
        ///540
        ///526
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncodingErrorInput {
            get {
                return ResourceManager.GetString("EncodingErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nop +612
        ///acc -6
        ///acc +41
        ///acc -4
        ///jmp +388
        ///acc +3
        ///acc +25
        ///acc +11
        ///nop +56
        ///jmp +110
        ///jmp +479
        ///jmp +129
        ///nop +436
        ///jmp +339
        ///acc -3
        ///acc -17
        ///acc -14
        ///acc +37
        ///jmp +24
        ///jmp +324
        ///jmp +233
        ///jmp +1
        ///acc +44
        ///acc +17
        ///nop +150
        ///jmp +163
        ///acc +0
        ///acc +10
        ///acc +49
        ///jmp +170
        ///acc +36
        ///jmp +339
        ///acc +28
        ///acc -8
        ///nop +194
        ///jmp +84
        ///acc +11
        ///jmp +241
        ///acc +0
        ///jmp +1
        ///acc +1
        ///jmp +370
        ///jmp +245
        ///jmp +235
        ///acc -6
        ///acc +27
        ///jmp +493
        ///nop +401
        ///acc +40
        ///acc +7
        ///jmp +562
        ///acc +6
        ///nop +472
        ///acc -7
        ///nop +508
        ///jmp +44
        ///nop +2
        ///jmp -6
        ///nop +542
        ///acc +1
        ///acc +34
        ///acc +39
        ///jmp +239
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HandheldHaltingInput {
            get {
                return ResourceManager.GetString("HandheldHaltingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plaid beige bags contain 3 drab magenta bags.
        ///dim silver bags contain 2 shiny chartreuse bags, 4 dull magenta bags.
        ///bright silver bags contain 2 faded maroon bags.
        ///shiny cyan bags contain 4 plaid green bags, 4 dim coral bags, 4 dull indigo bags.
        ///shiny orange bags contain 3 dim cyan bags, 1 mirrored beige bag, 5 pale orange bags.
        ///posh gray bags contain 5 dark bronze bags, 2 striped lavender bags, 3 light tan bags.
        ///clear lime bags contain 1 shiny crimson bag, 1 dark plum bag.
        ///wavy chartreuse bags contain 1 st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HandyHaversacksInput {
            get {
                return ResourceManager.GetString("HandyHaversacksInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:2015 cid:189 ecl:oth byr:1947 hcl:#6c4ab1 eyr:2026
        ///hgt:174cm
        ///pid:526744288
        ///
        ///pid:688706448 iyr:2017 hgt:162cm cid:174 ecl:grn byr:1943 hcl:#808e9e eyr:2025
        ///
        ///ecl:oth hcl:#733820 cid:124 pid:111220591
        ///iyr:2019 eyr:2001
        ///byr:1933 hgt:159in
        ///
        ///pid:812929897 hgt:159cm hcl:#fffffd byr:1942 iyr:2026 cid:291
        ///ecl:oth
        ///eyr:2024
        ///
        ///cid:83 pid:524032739 iyr:2013 ecl:amb byr:1974
        ///hgt:191cm hcl:#ceb3a1 eyr:2028
        ///
        ///ecl:gry hcl:eefed5 pid:88405792 hgt:183cm cid:221 byr:1963 eyr:2029
        ///
        ///pid:777881168 ecl:grn
        ///hgt:181cm byr:1923 eyr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PassportProcessingInput {
            get {
                return ResourceManager.GetString("PassportProcessingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-11 p: pppppppppxblp
        ///2-4 b: bbxbb
        ///3-5 q: dqfqb
        ///5-8 g: ggcgggglg
        ///10-18 l: gllpmlgtrmnllhllrlll
        ///18-19 z: zzzzznszzzzzzzzzzzxz
        ///3-6 r: frrhxsnrmgmw
        ///1-8 n: zkxhnxnzghnm
        ///11-12 z: zzczzzztlzlzzzz
        ///4-7 q: qqqbncqqq
        ///3-4 c: ccvfc
        ///19-20 l: sltlklljdlzglwllllzl
        ///6-16 h: dhhhrhvhnhdchfsnhq
        ///3-7 l: fllllqjlll
        ///8-9 k: xkkjqklkm
        ///1-2 l: llgpl
        ///2-4 x: qkjxvqlv
        ///5-6 c: cwcccjch
        ///3-7 n: bnnhnwnqtdnndnncnd
        ///8-9 n: nnrkmdnkn
        ///6-9 t: ttttrtltptgvcd
        ///3-4 h: hhwhhhdhhhh
        ///7-8 w: wdwvcwwszcwwwwwq
        ///2-4 n: vnng
        ///3-13 v: vvvvvvvvvvvvjv
        ///9-11 c: zccc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordPhilosophyInput {
            get {
                return ResourceManager.GetString("PasswordPhilosophyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F37
        ///E1
        ///S5
        ///R180
        ///S1
        ///F37
        ///L180
        ///F38
        ///S1
        ///E2
        ///L90
        ///F48
        ///N1
        ///S5
        ///E2
        ///F53
        ///E3
        ///L90
        ///F37
        ///S3
        ///F65
        ///L90
        ///F78
        ///W3
        ///S4
        ///L90
        ///F54
        ///F61
        ///E5
        ///S1
        ///L90
        ///W2
        ///L90
        ///N3
        ///F63
        ///S3
        ///E3
        ///F83
        ///R90
        ///S2
        ///W2
        ///S5
        ///E1
        ///R90
        ///W1
        ///R90
        ///W3
        ///F52
        ///E1
        ///S4
        ///E1
        ///E4
        ///R90
        ///E4
        ///F94
        ///N5
        ///F56
        ///F17
        ///L180
        ///W2
        ///S2
        ///R90
        ///S3
        ///F49
        ///R90
        ///N4
        ///E1
        ///N3
        ///F49
        ///R90
        ///S2
        ///E3
        ///F29
        ///E2
        ///R270
        ///E5
        ///L90
        ///W3
        ///F24
        ///E2
        ///S2
        ///L90
        ///F46
        ///N1
        ///F65
        ///E1
        ///N4
        ///E5
        ///R90
        ///S4
        ///L90
        ///F51
        ///R90
        ///L180
        ///W3
        ///R90
        ///L270
        ///W4
        ///S1
        ///W1
        ///L180
        ///S1
        ///F20
        ///E5
        ///L180
        ///N2
        ///F11
        ///R180
        ///N5
        ///E2
        ///N3
        ///L90
        ///F64
        ///N3
        ///W5
        ///L90
        ///W5
        ///S2
        ///F51
        ///L90
        ///F78
        ///W1
        ///R180
        ///F84
        ///R90
        ///W3
        ///L90
        ///F59
        ///S3
        ///R90
        ///R90
        ///E2
        ///F29
        ///R90
        ///F70
        ///S1
        ///F52
        ///L90
        ///N4
        ///E1
        ///F81
        ///W3
        ///F81
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RainRiskInput {
            get {
                return ResourceManager.GetString("RainRiskInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1429
        ///1368
        ///1661
        ///1687
        ///1593
        ///1495
        ///1565
        ///1500
        ///1635
        ///1845
        ///1645
        ///1999
        ///1415
        ///1054
        ///1930
        ///1774
        ///1405
        ///1993
        ///1757
        ///1623
        ///1675
        ///1665
        ///631
        ///1950
        ///1702
        ///1311
        ///1509
        ///1790
        ///1643
        ///1884
        ///226
        ///1455
        ///1679
        ///1746
        ///1284
        ///1342
        ///1684
        ///1543
        ///1396
        ///1806
        ///1523
        ///1363
        ///1011
        ///1577
        ///1767
        ///1287
        ///1885
        ///1517
        ///1556
        ///1722
        ///1260
        ///1624
        ///1466
        ///1263
        ///1162
        ///1688
        ///1202
        ///1913
        ///1964
        ///1385
        ///1970
        ///1976
        ///1431
        ///858
        ///1748
        ///1544
        ///1438
        ///1300
        ///1926
        ///1587
        ///1376
        ///1939
        ///1039
        ///1639
        ///1539
        ///1491
        ///1631
        ///1521
        ///1564
        ///1507
        ///1637
        ///1534
        ///1713
        ///1533
        ///1118
        ///1356
        ///2003
        ///282
        ///1079
        ///1837
        ///1259
        ///1941
        ///1836
        ///1903
        ///1433
        ///1467
        ///1027
        ///1441
        ///1048
        ///1742
        ///1087
        ///1872
        ///1476
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportRepairInput {
            get {
                return ResourceManager.GetString("ReportRepairInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1721
        ///979
        ///366
        ///299
        ///675
        ///1456
        ///.
        /// </summary>
        internal static string ReportRepairSampleInput {
            get {
                return ResourceManager.GetString("ReportRepairSampleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLLLLLLLLLLLLLLLLLLLLL.LLLLL..LLLLLLLLLLLL.LLL..LLLLLLLLLLLLLL.LL.LLLLL.LLLLLLLLL.LLLLLLLLLLLLL
        ///LLLLLLL.LLLLLLL.LLLLLLLLL.LLLLL.LLLL.LLLLLLLL.LLLLLLLLL.LLLL.LLLLLLLLLLLLLLLLLLLLLL..LLLLLLL..LLLL
        ///LLLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLLLL.LLL.LLLLLLLLLLLLLL.LLLLLLL..LLLLLLLLLLLLLLLLLLLLLL.LLLLL
        ///LLLLLLL.LLLLLLLLLLLLLLLLLLLLLLL.LLLL.LLLLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLL..LLLLLLLLL.LLLLLLL..LLLL
        ///.LLL.LL.LLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLL.LLLLL.LLLLLLLLL.LLLLLLLLLLLLL
        ///LL.LLLL.LLLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeatingSystemInput {
            get {
                return ResourceManager.GetString("SeatingSystemInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1002462
        ///37,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,41,x,x,x,x,x,x,x,x,x,601,x,x,x,x,x,x,x,x,x,x,x,19,x,x,x,x,17,x,x,x,x,x,23,x,x,x,x,x,29,x,443,x,x,x,x,x,x,x,x,x,x,x,x,13
        ///.
        /// </summary>
        internal static string ShuttleSearchInput {
            get {
                return ResourceManager.GetString("ShuttleSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ........#..#.##.#..............
        ///...#...............#.#.........
        ///...#..#...#..##....#...........
        ///...#.............#....#.....#..
        ///..#......#..#...#.......#......
        ///..............##...............
        ///#.......#.........#......#....#
        ///.#.....###.....#...#.#.#...#...
        ///#.....................#....#.#.
        ///.......#...................#...
        ///...#.#...................#....#
        ///....#....#.......#...#.........
        ///..##.#............#..#.........
        ///.....##.#..............##..###.
        ///...........#....#....#.........
        ///#.....#...#...#.#.#.#.##.#...#.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TobogganTrajectoryInput {
            get {
                return ResourceManager.GetString("TobogganTrajectoryInput", resourceCulture);
            }
        }
    }
}
