//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aoc2020.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aoc2020.Tests.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1429
        ///1368
        ///1661
        ///1687
        ///1593
        ///1495
        ///1565
        ///1500
        ///1635
        ///1845
        ///1645
        ///1999
        ///1415
        ///1054
        ///1930
        ///1774
        ///1405
        ///1993
        ///1757
        ///1623
        ///1675
        ///1665
        ///631
        ///1950
        ///1702
        ///1311
        ///1509
        ///1790
        ///1643
        ///1884
        ///226
        ///1455
        ///1679
        ///1746
        ///1284
        ///1342
        ///1684
        ///1543
        ///1396
        ///1806
        ///1523
        ///1363
        ///1011
        ///1577
        ///1767
        ///1287
        ///1885
        ///1517
        ///1556
        ///1722
        ///1260
        ///1624
        ///1466
        ///1263
        ///1162
        ///1688
        ///1202
        ///1913
        ///1964
        ///1385
        ///1970
        ///1976
        ///1431
        ///858
        ///1748
        ///1544
        ///1438
        ///1300
        ///1926
        ///1587
        ///1376
        ///1939
        ///1039
        ///1639
        ///1539
        ///1491
        ///1631
        ///1521
        ///1564
        ///1507
        ///1637
        ///1534
        ///1713
        ///1533
        ///1118
        ///1356
        ///2003
        ///282
        ///1079
        ///1837
        ///1259
        ///1941
        ///1836
        ///1903
        ///1433
        ///1467
        ///1027
        ///1441
        ///1048
        ///1742
        ///1087
        ///1872
        ///1476
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportRepairInput {
            get {
                return ResourceManager.GetString("ReportRepairInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1721
        ///979
        ///366
        ///299
        ///675
        ///1456
        ///.
        /// </summary>
        internal static string ReportRepairSampleInput {
            get {
                return ResourceManager.GetString("ReportRepairSampleInput", resourceCulture);
            }
        }
    }
}
